In [228]:
import json
import os
from datetime import datetime

# Train Particle Classifier(s): Control Panel
### Author: CG

This notebook succeeds the "train_region_classifiers.ipynb" notebook.

Here, we define a dictionary of input variables to initiate our particle detector training pipeline. This dictionary will be saved as a .json file and passed to the pipeline execution script, main.py

In [229]:
inputDict = {"sample_parent_directory": "/home/cameron/Dropbox (University of Michigan)/DL_training/data/classifier_training_samples",
             # Where to save the timestamped model
             "model_save_parent_directory": "data/models/code",
             # Specify codes to separately train the region detector on
             # Must be in format "(NUMBER)" as per our experimental convention for naming codes
             "code_list": ["(1)", "(2)", "(3)", "(4)", "(5)"],
             "strat_kfold": {"activate": True,
                             # Num. of folds
                             "num_folds": 5,
                             # Controls the splitting of data in a reproducible way if the same seed is used
                             "random_state": 100},
             # Activates hyperparameter optimization if True
             "hpo": {"activate": True,
                                 "hpo_file": "/home/cameron/Dropbox (University of Michigan)/DL_training/hpo/region_classifier_grid_search/hpo_trials_region_classifier.csv",
                                 # Save hyperparameter results every 'save_every' trials
                                 "save_every": 1,
                                 # Log via TensorBoard
                                 "log": True,
                                 # Timestamp corresponding to this particular hyperparameter optimization run,
                                 "hpo_timestamp": datetime.now().strftime("%m_%d_%y_%H:%M"),
                                 # Printing verbosity
                                 "verbose": False},
            }

# File save name
inputJSON = "train_particle_detector.json"
# Save
with open(inputJSON, "w") as jsonFile:
    json.dump(inputDict, jsonFile)

## Train Particle Detectors:

In [230]:
os.system(f"python main_cg_GPU.py --action train_code_classifier --pipeline_inputs {inputJSON}")

/home/cameron/Dropbox (University of Michigan)/DL_training/model_training/code_classification_trainer_GPU.py:238: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525552843/work/torch/csrc/utils/tensor_new.cpp:230.)
  samples = torch.as_tensor(samples, dtype=torch.float32)


CUDA Availability: True
FINAL VECTOR LENGTH: 64
Model Loaded to GPU: True
Code Map Between Sample Filenames and Internal Code Integer Designation:
{'(1)': 0, '(2)': 1, '(3)': 2, '(4)': 3, '(5)': 4}
Loaded 531 positive training samples
Loaded 401 positive training samples
Loaded 293 positive training samples
Loaded 348 positive training samples
Loaded 190 positive training samples
Total Composite Dataset Training Samples:
1763


Fold 1
CUDA Availability: True
FINAL VECTOR LENGTH: 64
Model Loaded to GPU: True
Code Map Between Sample Filenames and Internal Code Integer Designation:
{'(1)': 0, '(2)': 1, '(3)': 2, '(4)': 3, '(5)': 4}


Epoch 0::   0%|          | 0/4 [00:00<?, ?it/s]/home/cameron/Dropbox (University of Michigan)/DL_training/model_training/code_classification_trainer_GPU.py:118: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  predictedLabels = torch.tensor((torch.argmax(predictions, dim=1) + 1).float(), requires_grad=True)
Epoch 0:: 100%|██████████| 4/4 [00:01<00:00,  3.13it/s]


LOSS
tensor(3354.2727, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3442.2058, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3377.9841, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3425.4409, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1961, 0.1867, 0.1818, 0.2241, 0.2114],
        [0.2011, 0.1797, 0.1854, 0.2179, 0.2159],
        [0.2038, 0.1789, 0.1788, 0.2189, 0.2197],
        ...,
        [0.2035, 0.1770, 0.1778, 0.2176, 0.2241],
        [0.1987, 0.1872, 0.1824, 0.2202, 0.2115],
        [0.1901, 0.1785, 0.1909, 0.2233, 0.2172]], device='cuda:0')
data/models/code


Epoch 1:: 100%|██████████| 4/4 [00:00<00:00, 169.01it/s]


LOSS
tensor(3282.1543, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3457.4326, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3335.1418, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3590.1079, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.2049, 0.1666, 0.1880, 0.2348, 0.2058],
        [0.2105, 0.1595, 0.1975, 0.2246, 0.2080],
        [0.2147, 0.1622, 0.1850, 0.2236, 0.2146],
        ...,
        [0.2152, 0.1565, 0.1864, 0.2228, 0.2191],
        [0.2095, 0.1706, 0.1893, 0.2259, 0.2048],
        [0.1980, 0.1620, 0.2004, 0.2291, 0.2105]], device='cuda:0')


Epoch 2:: 100%|██████████| 4/4 [00:00<00:00, 172.07it/s]


LOSS
tensor(3444.7126, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3297.8257, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3520.9722, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3368.8965, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.2035, 0.1533, 0.1974, 0.2465, 0.1993],
        [0.2094, 0.1490, 0.2056, 0.2380, 0.1979],
        [0.2162, 0.1508, 0.1944, 0.2303, 0.2084],
        ...,
        [0.2178, 0.1417, 0.1916, 0.2346, 0.2143],
        [0.2070, 0.1587, 0.1963, 0.2385, 0.1996],
        [0.1972, 0.1495, 0.2111, 0.2377, 0.2045]], device='cuda:0')


Epoch 3:: 100%|██████████| 4/4 [00:00<00:00, 169.43it/s]


LOSS
tensor(3333.0469, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3454.2070, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3611.4622, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3395.6685, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.2125, 0.1440, 0.2072, 0.2445, 0.1917],
        [0.2211, 0.1395, 0.2179, 0.2315, 0.1901],
        [0.2284, 0.1407, 0.2013, 0.2222, 0.2075],
        ...,
        [0.2406, 0.1250, 0.1930, 0.2283, 0.2130],
        [0.2199, 0.1567, 0.2015, 0.2351, 0.1869],
        [0.2115, 0.1342, 0.2244, 0.2275, 0.2024]], device='cuda:0')


Epoch 4:: 100%|██████████| 4/4 [00:00<00:00, 168.46it/s]


LOSS
tensor(3574.8008, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3431., device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3339.0144, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3318.4688, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.2182, 0.1339, 0.2070, 0.2502, 0.1907],
        [0.2230, 0.1311, 0.2289, 0.2312, 0.1858],
        [0.2260, 0.1373, 0.2068, 0.2233, 0.2066],
        ...,
        [0.2556, 0.1090, 0.1946, 0.2254, 0.2155],
        [0.2208, 0.1581, 0.2046, 0.2375, 0.1790],
        [0.2099, 0.1226, 0.2376, 0.2230, 0.2069]], device='cuda:0')


Epoch 5:: 100%|██████████| 4/4 [00:00<00:00, 158.48it/s]


LOSS
tensor(3344.3081, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3528.2766, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3384.7524, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3321.1919, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.2204, 0.1252, 0.2091, 0.2609, 0.1845],
        [0.2143, 0.1211, 0.2486, 0.2372, 0.1788],
        [0.2147, 0.1402, 0.2142, 0.2302, 0.2006],
        ...,
        [0.2628, 0.0955, 0.2006, 0.2296, 0.2115],
        [0.2159, 0.1636, 0.2122, 0.2448, 0.1635],
        [0.1960, 0.1125, 0.2624, 0.2251, 0.2041]], device='cuda:0')


Epoch 6:: 100%|██████████| 4/4 [00:00<00:00, 169.69it/s]


LOSS
tensor(3424.9487, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3565.5071, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3278.8647, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3389.1951, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.2342, 0.1160, 0.2064, 0.2546, 0.1888],
        [0.2202, 0.1129, 0.2788, 0.2131, 0.1750],
        [0.2108, 0.1432, 0.2218, 0.2181, 0.2061],
        ...,
        [0.2806, 0.0851, 0.2049, 0.2190, 0.2105],
        [0.2222, 0.1746, 0.2169, 0.2337, 0.1526],
        [0.1860, 0.1008, 0.2844, 0.2202, 0.2086]], device='cuda:0')


Epoch 7:: 100%|██████████| 4/4 [00:00<00:00, 168.03it/s]


LOSS
tensor(3470.8679, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3416.9316, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3329.5312, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3359.4075, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.2476, 0.1109, 0.2095, 0.2443, 0.1877],
        [0.2186, 0.1042, 0.3124, 0.1906, 0.1743],
        [0.2104, 0.1491, 0.2273, 0.1997, 0.2136],
        ...,
        [0.2958, 0.0795, 0.2100, 0.2072, 0.2075],
        [0.2315, 0.1843, 0.2187, 0.2237, 0.1418],
        [0.1719, 0.0963, 0.3025, 0.2188, 0.2105]], device='cuda:0')


Epoch 8:: 100%|██████████| 4/4 [00:00<00:00, 168.88it/s]


LOSS
tensor(3490.3359, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3212.4336, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3392.0464, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3516.6826, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.2572, 0.1110, 0.2002, 0.2426, 0.1890],
        [0.2176, 0.1021, 0.3258, 0.1798, 0.1747],
        [0.2105, 0.1533, 0.2258, 0.1950, 0.2153],
        ...,
        [0.2989, 0.0750, 0.2063, 0.2053, 0.2145],
        [0.2252, 0.1992, 0.2125, 0.2260, 0.1370],
        [0.1570, 0.0963, 0.3107, 0.2199, 0.2162]], device='cuda:0')


Epoch 9:: 100%|██████████| 4/4 [00:00<00:00, 158.62it/s]


LOSS
tensor(3389.1545, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3400.5254, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3411.5254, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3505.3159, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.2822, 0.1144, 0.1964, 0.2222, 0.1847],
        [0.2154, 0.0954, 0.3628, 0.1592, 0.1673],
        [0.2129, 0.1614, 0.2295, 0.1754, 0.2209],
        ...,
        [0.3139, 0.0732, 0.2026, 0.1903, 0.2201],
        [0.2328, 0.2106, 0.2099, 0.2148, 0.1320],
        [0.1403, 0.0921, 0.3276, 0.2177, 0.2224]], device='cuda:0')


Epoch 10:: 100%|██████████| 4/4 [00:00<00:00, 161.72it/s]


LOSS
tensor(3342.9246, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3565.1851, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3350.7659, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3372.1169, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.3075, 0.1185, 0.1924, 0.2029, 0.1787],
        [0.2134, 0.0920, 0.3913, 0.1416, 0.1617],
        [0.2134, 0.1732, 0.2341, 0.1567, 0.2225],
        ...,
        [0.3239, 0.0731, 0.1954, 0.1781, 0.2294],
        [0.2346, 0.2266, 0.2027, 0.2036, 0.1326],
        [0.1296, 0.0906, 0.3399, 0.2118, 0.2281]], device='cuda:0')
data/models/code


Epoch 11:: 100%|██████████| 4/4 [00:00<00:00, 174.92it/s]


LOSS
tensor(3380.6724, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3442.1948, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3568.9224, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3496.5576, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.3078, 0.1219, 0.1916, 0.2069, 0.1718],
        [0.2116, 0.0988, 0.3867, 0.1420, 0.1609],
        [0.2119, 0.1810, 0.2287, 0.1655, 0.2129],
        ...,
        [0.3219, 0.0747, 0.1901, 0.1801, 0.2332],
        [0.2244, 0.2421, 0.2009, 0.2063, 0.1263],
        [0.1231, 0.0918, 0.3473, 0.2171, 0.2208]], device='cuda:0')


Epoch 12:: 100%|██████████| 4/4 [00:00<00:00, 168.17it/s]


LOSS
tensor(3331.8918, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3487.1082, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3376.0525, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3491.6729, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.3321, 0.1235, 0.1845, 0.1918, 0.1682],
        [0.2095, 0.0947, 0.4041, 0.1318, 0.1599],
        [0.2130, 0.1913, 0.2282, 0.1517, 0.2158],
        ...,
        [0.3262, 0.0750, 0.1829, 0.1682, 0.2478],
        [0.2263, 0.2518, 0.1934, 0.2001, 0.1284],
        [0.1150, 0.0907, 0.3524, 0.2101, 0.2317]], device='cuda:0')


Epoch 13:: 100%|██████████| 4/4 [00:00<00:00, 171.26it/s]


LOSS
tensor(3549.5986, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3336.7317, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3412.2388, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3371.0303, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.3519, 0.1226, 0.1784, 0.1813, 0.1658],
        [0.2055, 0.0915, 0.4182, 0.1270, 0.1579],
        [0.2138, 0.1985, 0.2266, 0.1451, 0.2160],
        ...,
        [0.3289, 0.0767, 0.1773, 0.1599, 0.2573],
        [0.2317, 0.2590, 0.1848, 0.1977, 0.1269],
        [0.1097, 0.0929, 0.3562, 0.2072, 0.2340]], device='cuda:0')


Epoch 14:: 100%|██████████| 4/4 [00:00<00:00, 162.34it/s]


LOSS
tensor(3267.5525, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3456.6240, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3478.8345, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3370.5874, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.3368, 0.1206, 0.1844, 0.1862, 0.1721],
        [0.2102, 0.0910, 0.4102, 0.1303, 0.1583],
        [0.2112, 0.1778, 0.2421, 0.1501, 0.2189],
        ...,
        [0.3285, 0.0734, 0.1817, 0.1653, 0.2511],
        [0.2279, 0.2402, 0.2008, 0.2000, 0.1311],
        [0.1118, 0.0918, 0.3531, 0.2088, 0.2346]], device='cuda:0')


Epoch 15:: 100%|██████████| 4/4 [00:00<00:00, 167.52it/s]


LOSS
tensor(3378.8901, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3457.3306, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3366.5869, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3481.9473, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.3519, 0.1225, 0.1832, 0.1736, 0.1689],
        [0.2078, 0.0894, 0.4252, 0.1224, 0.1552],
        [0.2120, 0.1880, 0.2441, 0.1396, 0.2162],
        ...,
        [0.3310, 0.0752, 0.1809, 0.1581, 0.2548],
        [0.2286, 0.2521, 0.1968, 0.1924, 0.1300],
        [0.1080, 0.0927, 0.3554, 0.2046, 0.2392]], device='cuda:0')


Fold 2
CUDA Availability: True
FINAL VECTOR LENGTH: 64
Model Loaded to GPU: True
Code Map Between Sample Filenames and Internal Code Integer Designation:
{'(1)': 0, '(2)': 1, '(3)': 2, '(4)': 3, '(5)': 4}


Epoch 0:: 100%|██████████| 4/4 [00:00<00:00, 168.06it/s]


LOSS
tensor(3395.2114, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3348.9397, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3470.9648, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3433.4736, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1008, 0.2703, 0.0873, 0.3547, 0.1869],
        [0.1079, 0.2574, 0.0864, 0.3609, 0.1874],
        [0.0949, 0.2610, 0.0919, 0.3615, 0.1907],
        ...,
        [0.0940, 0.2412, 0.0884, 0.3871, 0.1893],
        [0.0977, 0.2445, 0.0913, 0.3788, 0.1877],
        [0.0973, 0.2599, 0.0915, 0.3651, 0.1862]], device='cuda:0')
data/models/code


Epoch 1:: 100%|██████████| 4/4 [00:00<00:00, 169.69it/s]


LOSS
tensor(3459.0474, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3316.0232, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3265.6572, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3354.4165, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1300, 0.2653, 0.1047, 0.2987, 0.2013],
        [0.1368, 0.2533, 0.1038, 0.3089, 0.1972],
        [0.1194, 0.2578, 0.1136, 0.3048, 0.2044],
        ...,
        [0.1193, 0.2441, 0.1133, 0.3218, 0.2014],
        [0.1238, 0.2408, 0.1127, 0.3217, 0.2010],
        [0.1251, 0.2619, 0.1126, 0.3047, 0.1956]], device='cuda:0')


Epoch 2:: 100%|██████████| 4/4 [00:00<00:00, 172.02it/s]


LOSS
tensor(3379.2207, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3387.2664, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3289.7832, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3330.5635, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1286, 0.2848, 0.0926, 0.2920, 0.2020],
        [0.1357, 0.2672, 0.0906, 0.3127, 0.1938],
        [0.1091, 0.2828, 0.1051, 0.2989, 0.2041],
        ...,
        [0.1141, 0.2562, 0.1081, 0.3254, 0.1961],
        [0.1203, 0.2494, 0.1063, 0.3249, 0.1991],
        [0.1203, 0.2879, 0.1039, 0.2970, 0.1909]], device='cuda:0')


Epoch 3:: 100%|██████████| 4/4 [00:00<00:00, 169.91it/s]


LOSS
tensor(3542.0312, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3291.8132, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3319.0022, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3357.5901, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1363, 0.2935, 0.0886, 0.2810, 0.2006],
        [0.1457, 0.2774, 0.0833, 0.2996, 0.1940],
        [0.1102, 0.3058, 0.1021, 0.2769, 0.2049],
        ...,
        [0.1213, 0.2640, 0.1097, 0.3159, 0.1890],
        [0.1285, 0.2580, 0.1061, 0.3108, 0.1966],
        [0.1248, 0.3118, 0.1030, 0.2753, 0.1852]], device='cuda:0')


Epoch 4:: 100%|██████████| 4/4 [00:00<00:00, 170.01it/s]


LOSS
tensor(3318.8430, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3528.3179, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3295.5610, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3301.9788, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1328, 0.3074, 0.0781, 0.2825, 0.1992],
        [0.1445, 0.3035, 0.0706, 0.2938, 0.1875],
        [0.0941, 0.3547, 0.0926, 0.2587, 0.1999],
        ...,
        [0.1139, 0.2770, 0.1040, 0.3215, 0.1836],
        [0.1216, 0.2671, 0.0964, 0.3214, 0.1935],
        [0.1140, 0.3600, 0.0947, 0.2614, 0.1698]], device='cuda:0')


Epoch 5:: 100%|██████████| 4/4 [00:00<00:00, 171.85it/s]


LOSS
tensor(3367.4150, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3421.1938, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3528.2778, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3134.4102, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1345, 0.3190, 0.0707, 0.2826, 0.1932],
        [0.1460, 0.3133, 0.0622, 0.2970, 0.1815],
        [0.0831, 0.3981, 0.0859, 0.2396, 0.1933],
        ...,
        [0.1123, 0.2868, 0.0996, 0.3215, 0.1797],
        [0.1203, 0.2675, 0.0900, 0.3283, 0.1940],
        [0.1083, 0.4079, 0.0923, 0.2419, 0.1496]], device='cuda:0')


Epoch 6:: 100%|██████████| 4/4 [00:00<00:00, 169.85it/s]


LOSS
tensor(3347.2603, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3123.4009, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3489.8398, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3568.4507, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1300, 0.3209, 0.0646, 0.2895, 0.1950],
        [0.1386, 0.3098, 0.0535, 0.3170, 0.1811],
        [0.0696, 0.4444, 0.0846, 0.2181, 0.1834],
        ...,
        [0.1068, 0.2868, 0.0980, 0.3303, 0.1781],
        [0.1122, 0.2632, 0.0871, 0.3373, 0.2001],
        [0.0993, 0.4531, 0.0947, 0.2194, 0.1334]], device='cuda:0')


Epoch 7:: 100%|██████████| 4/4 [00:00<00:00, 167.39it/s]


LOSS
tensor(3609.1616, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3332.3965, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3206.4087, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3365.2329, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1302, 0.3130, 0.0599, 0.2937, 0.2032],
        [0.1381, 0.2784, 0.0466, 0.3462, 0.1906],
        [0.0663, 0.4600, 0.0842, 0.2054, 0.1840],
        ...,
        [0.1078, 0.2771, 0.1006, 0.3306, 0.1839],
        [0.1097, 0.2446, 0.0849, 0.3452, 0.2156],
        [0.0993, 0.4788, 0.0982, 0.1961, 0.1277]], device='cuda:0')


Epoch 8:: 100%|██████████| 4/4 [00:00<00:00, 170.34it/s]


LOSS
tensor(3144.2031, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3432.6335, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3305.8188, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3453.6426, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1241, 0.3065, 0.0582, 0.2983, 0.2129],
        [0.1344, 0.2518, 0.0399, 0.3782, 0.1957],
        [0.0573, 0.4827, 0.0838, 0.1932, 0.1830],
        ...,
        [0.1046, 0.2693, 0.1025, 0.3415, 0.1821],
        [0.0971, 0.2417, 0.0810, 0.3599, 0.2203],
        [0.0978, 0.5007, 0.1041, 0.1718, 0.1256]], device='cuda:0')


Epoch 9:: 100%|██████████| 4/4 [00:00<00:00, 157.80it/s]


LOSS
tensor(3349.3369, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3341.7251, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3528.5552, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3277.1562, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1435, 0.2964, 0.0594, 0.2910, 0.2097],
        [0.1576, 0.2325, 0.0429, 0.3706, 0.1964],
        [0.0709, 0.4653, 0.0896, 0.1813, 0.1929],
        ...,
        [0.1219, 0.2720, 0.1127, 0.3098, 0.1836],
        [0.1121, 0.2210, 0.0844, 0.3491, 0.2333],
        [0.1084, 0.4890, 0.1103, 0.1619, 0.1305]], device='cuda:0')


Epoch 10:: 100%|██████████| 4/4 [00:00<00:00, 171.73it/s]


LOSS
tensor(3358.5037, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3247.4797, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3365.1934, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3442.9636, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1327, 0.2940, 0.0594, 0.2957, 0.2183],
        [0.1512, 0.2126, 0.0380, 0.3978, 0.2005],
        [0.0613, 0.4881, 0.0883, 0.1729, 0.1896],
        ...,
        [0.1188, 0.2628, 0.1161, 0.3189, 0.1834],
        [0.0980, 0.2251, 0.0817, 0.3625, 0.2327],
        [0.1055, 0.5095, 0.1159, 0.1431, 0.1260]], device='cuda:0')
data/models/code


Epoch 11:: 100%|██████████| 4/4 [00:00<00:00, 169.38it/s]


LOSS
tensor(3286.6719, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3499.3574, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3415.8394, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3308.4897, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1296, 0.2954, 0.0575, 0.2977, 0.2199],
        [0.1455, 0.1983, 0.0347, 0.4153, 0.2062],
        [0.0583, 0.4956, 0.0883, 0.1687, 0.1891],
        ...,
        [0.1158, 0.2554, 0.1214, 0.3202, 0.1872],
        [0.0918, 0.2249, 0.0796, 0.3717, 0.2321],
        [0.1032, 0.5178, 0.1171, 0.1347, 0.1272]], device='cuda:0')


Epoch 12:: 100%|██████████| 4/4 [00:00<00:00, 137.38it/s]


LOSS
tensor(3360.0925, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3341.7292, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3271.0220, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3302.6594, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1275, 0.2946, 0.0540, 0.3020, 0.2220],
        [0.1391, 0.1759, 0.0314, 0.4382, 0.2153],
        [0.0573, 0.4944, 0.0858, 0.1693, 0.1932],
        ...,
        [0.1161, 0.2459, 0.1226, 0.3244, 0.1911],
        [0.0897, 0.2184, 0.0753, 0.3813, 0.2353],
        [0.1050, 0.5180, 0.1154, 0.1317, 0.1299]], device='cuda:0')


Epoch 13:: 100%|██████████| 4/4 [00:00<00:00, 159.51it/s]


LOSS
tensor(3255.4819, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3385.4841, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3445.7427, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3476.4570, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1210, 0.2950, 0.0534, 0.3025, 0.2280],
        [0.1394, 0.1726, 0.0300, 0.4448, 0.2132],
        [0.0541, 0.5046, 0.0852, 0.1636, 0.1925],
        ...,
        [0.1159, 0.2380, 0.1247, 0.3314, 0.1899],
        [0.0817, 0.2191, 0.0718, 0.3989, 0.2285],
        [0.1029, 0.5317, 0.1121, 0.1254, 0.1279]], device='cuda:0')


Epoch 14:: 100%|██████████| 4/4 [00:00<00:00, 172.77it/s]


LOSS
tensor(3171.3186, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3509.9219, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3350.2485, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3441.0474, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1195, 0.2913, 0.0513, 0.3021, 0.2356],
        [0.1359, 0.1669, 0.0292, 0.4482, 0.2198],
        [0.0535, 0.5078, 0.0839, 0.1603, 0.1944],
        ...,
        [0.1170, 0.2388, 0.1273, 0.3243, 0.1926],
        [0.0795, 0.2193, 0.0714, 0.4000, 0.2299],
        [0.1026, 0.5393, 0.1080, 0.1203, 0.1299]], device='cuda:0')


Epoch 15:: 100%|██████████| 4/4 [00:00<00:00, 166.36it/s]


LOSS
tensor(3426.5869, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3301.1021, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3584.9238, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3289.2036, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1107, 0.2879, 0.0521, 0.3138, 0.2355],
        [0.1326, 0.1617, 0.0282, 0.4631, 0.2144],
        [0.0511, 0.5101, 0.0856, 0.1638, 0.1895],
        ...,
        [0.1114, 0.2324, 0.1261, 0.3406, 0.1895],
        [0.0733, 0.2198, 0.0715, 0.4113, 0.2242],
        [0.0974, 0.5504, 0.1107, 0.1187, 0.1227]], device='cuda:0')


Fold 3
CUDA Availability: True
FINAL VECTOR LENGTH: 64
Model Loaded to GPU: True
Code Map Between Sample Filenames and Internal Code Integer Designation:
{'(1)': 0, '(2)': 1, '(3)': 2, '(4)': 3, '(5)': 4}


Epoch 0:: 100%|██████████| 4/4 [00:00<00:00, 171.41it/s]


LOSS
tensor(3414.9856, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3353.1890, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3376.2344, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3504.5039, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.2043, 0.1794, 0.2083, 0.1867, 0.2213],
        [0.2111, 0.1878, 0.2107, 0.1834, 0.2070],
        [0.2098, 0.1834, 0.2002, 0.1874, 0.2192],
        ...,
        [0.2064, 0.1842, 0.2020, 0.1831, 0.2243],
        [0.2027, 0.1846, 0.2026, 0.1901, 0.2200],
        [0.2108, 0.1826, 0.2046, 0.1855, 0.2166]], device='cuda:0')
data/models/code


Epoch 1:: 100%|██████████| 4/4 [00:00<00:00, 165.82it/s]


LOSS
tensor(3366.8506, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3354.7397, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3423.4551, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3529.9312, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1799, 0.1735, 0.2039, 0.1947, 0.2481],
        [0.1938, 0.1825, 0.2083, 0.1936, 0.2219],
        [0.1933, 0.1766, 0.1928, 0.1987, 0.2387],
        ...,
        [0.1845, 0.1794, 0.1949, 0.1899, 0.2513],
        [0.1802, 0.1793, 0.1940, 0.2032, 0.2432],
        [0.1883, 0.1802, 0.1983, 0.1964, 0.2369]], device='cuda:0')


Epoch 2:: 100%|██████████| 4/4 [00:00<00:00, 162.80it/s]


LOSS
tensor(3549.7341, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3443.5840, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3476.8906, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3417.8064, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1639, 0.1645, 0.1892, 0.2091, 0.2733],
        [0.1772, 0.1735, 0.1971, 0.2124, 0.2398],
        [0.1787, 0.1713, 0.1828, 0.2150, 0.2523],
        ...,
        [0.1664, 0.1769, 0.1777, 0.2034, 0.2755],
        [0.1627, 0.1705, 0.1795, 0.2228, 0.2644],
        [0.1699, 0.1717, 0.1898, 0.2123, 0.2563]], device='cuda:0')


Epoch 3:: 100%|██████████| 4/4 [00:00<00:00, 159.65it/s]


LOSS
tensor(3559.4380, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3317.5420, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3567.3511, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3349.4004, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1416, 0.1625, 0.1988, 0.2048, 0.2923],
        [0.1645, 0.1732, 0.1990, 0.2235, 0.2399],
        [0.1720, 0.1707, 0.1800, 0.2263, 0.2510],
        ...,
        [0.1470, 0.1820, 0.1739, 0.2051, 0.2919],
        [0.1448, 0.1699, 0.1775, 0.2360, 0.2717],
        [0.1496, 0.1707, 0.1889, 0.2244, 0.2664]], device='cuda:0')


Epoch 4:: 100%|██████████| 4/4 [00:00<00:00, 167.00it/s]


LOSS
tensor(3400.4446, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3597.4058, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3517.5869, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3404.5020, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1240, 0.1606, 0.2094, 0.2008, 0.3052],
        [0.1594, 0.1673, 0.1914, 0.2421, 0.2398],
        [0.1672, 0.1671, 0.1761, 0.2396, 0.2500],
        ...,
        [0.1347, 0.1823, 0.1616, 0.2066, 0.3148],
        [0.1344, 0.1596, 0.1738, 0.2558, 0.2764],
        [0.1358, 0.1678, 0.1796, 0.2384, 0.2783]], device='cuda:0')


Epoch 5:: 100%|██████████| 4/4 [00:00<00:00, 170.35it/s]


LOSS
tensor(3503.2336, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3449.5259, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3337.5864, device='cuda:0', grad_fn=<DivBackward1>)
LOSS
tensor(3378.7944, device='cuda:0', grad_fn=<DivBackward1>)
TEST PREDICTIONS
tensor([[0.1126, 0.1575, 0.2180, 0.1977, 0.3142],
        [0.1591, 0.1580, 0.1812, 0.2698, 0.2320],
        [0.1665, 0.1634, 0.1733, 0.2532, 0.2436],
        ...,
        [0.1252, 0.1784, 0.1520, 0.2081, 0.3364],
        [0.1282, 0.1479, 0.1693, 0.2811, 0.2735],
        [0.1236, 0.1595, 0.1706, 0.2568, 0.2895]], device='cuda:0')


Traceback (most recent call last):
  File "/home/cameron/Dropbox (University of Michigan)/DL_training/main_cg_GPU.py", line 837, in <module>
    train_code_classifier(pipeline_inputs=pipeline_inputs)
  File "/home/cameron/Dropbox (University of Michigan)/DL_training/main_cg_GPU.py", line 619, in train_code_classifier
    crossValScores = trainer.train(crossVal=pipeline_inputs["strat_kfold"]["activate"], 
  File "/home/cameron/Dropbox (University of Michigan)/DL_training/model_training/code_classification_trainer_GPU.py", line 109, in train
    batches = self.generate_batches(train_data)
  File "/home/cameron/Dropbox (University of Michigan)/DL_training/model_training/code_classification_trainer_GPU.py", line 238, in generate_batches
    samples = torch.as_tensor(samples, dtype=torch.float32)
KeyboardInterrupt


2